import "@/globals.css";
import Footer from "@/src/components/footer";
import Header from "@/src/components/header";

export const metadata = {
  title: "Adeir",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: any;
}) {
  return (
    <html lang="en">
      <body>
        <Header lang={lang} />
        <main className="min-h-screen py-10 px-8">{children}</main>
        <Footer lang={lang}/>
      </body>
    </html>
  );
}
